
# Site Settings
locale: "en"
name: Dustin Yost
title: "Dustin Yost"
title_separator: "-"
description: ""
url: "https://temportalflux.github.io"
baseurl: ""
repository: "temportalflux/temportalflux.github.io"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Social Sharing
twitter:
  username:
github:
  username: "temportalflux"
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: Person # Person or Organization (defaults to Person)
  name: Dustin Yost # If the user or organization name differs from the site's name
  links:
    - "https://github.com/temportalflux"
    - "https://www.linkedin.com/in/dustin-yost"

# Site Author
author:
  name             : "Dustin Yost"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "An explorer of digital time and space"
  location         : "Burlington, VT"
  locationLink     : "https://www.google.com/maps/place/Burlington,+VT/"
  email            : "dustin.yost.t@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "temportalflux"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "dustin-yost"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :

markdown: kramdown
permalink: /posts/:year/:month/:day/:title
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: false

collections:
  projects:
    output: true
    permalink: /:collection/:path/
